const currentLocation = {
  name: "강남역 11번 출구 근처",
  description: "샘플 데이터 기준 현재 위치",
  lat: 37.498095,
  lng: 127.02761,
};

const benefits = [
  {
    id: "mega-t-400",
    brand: "메가MGC커피",
    branch: "강남역점",
    category: "카페",
    distance: 42,
    benefitType: "discount",
    benefitLabel: "400원 할인",
    title: "아메리카노 1잔당 400원 할인",
    description: "T멤버십 바코드 제시 시 제조 음료 일부 메뉴에 적용됩니다.",
    provider: "T멤버십",
    providerType: "통신사",
    appName: "T멤버십",
    appScheme: "tworldmembership://",
    fallbackUrl: "https://www.sktmembership.co.kr/",
    saving: 400,
    expiresAt: "오늘 23:59",
    accent: "#ffd400",
    logoText: "MEGA",
    logoSub: "MGC",
    brandColor: "#ffd400",
    logoTextColor: "#1f2433",
    titleColor: "#1f2433",
  },
  {
    id: "compose-oneplus",
    brand: "컴포즈커피",
    branch: "강남대로점",
    category: "카페",
    distance: 68,
    benefitType: "oneplus",
    benefitLabel: "1+1",
    title: "아이스 아메리카노 1+1 이벤트",
    description: "컴포즈커피 앱 쿠폰함에서 오늘의 1+1 쿠폰을 확인할 수 있습니다.",
    provider: "컴포즈커피",
    providerType: "브랜드 앱",
    appName: "컴포즈커피 앱",
    appScheme: "composecoffee://",
    fallbackUrl: "https://composecoffee.com/",
    saving: 1500,
    expiresAt: "오늘 한정",
    accent: "#0054a6",
    logoText: "COMPOSE",
    logoSub: "COFFEE",
    brandColor: "#0054a6",
    logoTextColor: "#ffdd2d",
    titleColor: "#0054a6",
  },
  {
    id: "starbucks-sizeup",
    brand: "스타벅스",
    branch: "강남R점",
    category: "카페",
    distance: 92,
    benefitType: "upgrade",
    benefitLabel: "사이즈업",
    title: "제조 음료 무료 사이즈업",
    description: "스타벅스 앱 사이렌오더 또는 매장 주문 시 이벤트 쿠폰을 사용할 수 있습니다.",
    provider: "스타벅스",
    providerType: "브랜드 앱",
    appName: "스타벅스 앱",
    appScheme: "starbucks://",
    fallbackUrl: "https://www.starbucks.co.kr/",
    saving: 500,
    expiresAt: "이번 주",
    accent: "#006241",
    logoText: "STAR",
    logoSub: "BUCKS",
    brandColor: "#006241",
    logoTextColor: "#ffffff",
  },
  {
    id: "paik-coffee-card",
    brand: "빽다방",
    branch: "강남CGV옆점",
    category: "카페",
    distance: 134,
    benefitType: "discount",
    benefitLabel: "10% 할인",
    title: "현대카드 결제 시 10% 청구 할인",
    description: "현대카드 앱에서 혜택 응모 후 7천원 이상 결제하면 적용됩니다.",
    provider: "현대카드",
    providerType: "카드",
    appName: "현대카드 앱",
    appScheme: "hyundaicardappcardansimclick://",
    fallbackUrl: "https://www.hyundaicard.com/",
    saving: 700,
    expiresAt: "D-3",
    accent: "#111111",
    logoText: "PAIK'S",
    logoSub: "COFFEE",
    brandColor: "#111111",
    logoTextColor: "#ffdf2e",
  },
  {
    id: "ediya-pay",
    brand: "이디야커피",
    branch: "역삼중앙점",
    category: "카페",
    distance: 214,
    benefitType: "coupon",
    benefitLabel: "쿠폰",
    title: "카카오페이 1천원 즉시 할인",
    description: "카카오페이 결제 화면에서 이디야 전용 쿠폰을 선택하면 적용됩니다.",
    provider: "카카오페이",
    providerType: "간편결제",
    appName: "카카오페이",
    appScheme: "kakaotalk://",
    fallbackUrl: "https://www.kakaopay.com/",
    saving: 1000,
    expiresAt: "오늘 22:00",
    accent: "#ffcd00",
    logoText: "EDIYA",
    logoSub: "COFFEE",
    brandColor: "#173f8a",
    logoTextColor: "#ffffff",
  },
  {
    id: "twosome-membership",
    brand: "투썸플레이스",
    branch: "강남대로점",
    category: "카페",
    distance: 286,
    benefitType: "discount",
    benefitLabel: "15% 할인",
    title: "멤버십 등급 쿠폰 15% 할인",
    description: "투썸하트 앱에서 쿠폰을 내려받고 매장 결제 전에 제시하세요.",
    provider: "투썸하트",
    providerType: "브랜드 앱",
    appName: "투썸하트 앱",
    appScheme: "twosome://",
    fallbackUrl: "https://www.twosome.co.kr/",
    saving: 1200,
    expiresAt: "D-5",
    accent: "#a31621",
    logoText: "A TWOSOME",
    logoSub: "PLACE",
    brandColor: "#8b1118",
    logoTextColor: "#ffffff",
  },
  {
    id: "gs25-oneplus",
    brand: "GS25",
    branch: "강남역삼점",
    category: "편의점",
    distance: 352,
    benefitType: "oneplus",
    benefitLabel: "1+1",
    title: "커피 음료 1+1 행사",
    description: "우리동네GS 앱 행사상품에서 대상 음료를 확인할 수 있습니다.",
    provider: "우리동네GS",
    providerType: "브랜드 앱",
    appName: "우리동네GS",
    appScheme: "thepop://",
    fallbackUrl: "https://gsretail.com/",
    saving: 1800,
    expiresAt: "이번 달",
    accent: "#1f75cb",
    logoText: "GS25",
    logoSub: "편의점",
    brandColor: "#1f75cb",
    logoTextColor: "#ffffff",
  },
  {
    id: "cgv-popcorn",
    brand: "CGV",
    branch: "강남",
    category: "영화관",
    distance: 640,
    benefitType: "coupon",
    benefitLabel: "콤보 할인",
    title: "T멤버십 영화 콤보 2천원 할인",
    description: "T멤버십 앱에서 CGV 매점 할인 바코드를 열어 사용할 수 있습니다.",
    provider: "T멤버십",
    providerType: "통신사",
    appName: "T멤버십",
    appScheme: "tworldmembership://",
    fallbackUrl: "https://www.sktmembership.co.kr/",
    saving: 2000,
    expiresAt: "상시",
    accent: "#d71920",
    logoText: "CGV",
    logoSub: "CINEMA",
    brandColor: "#d71920",
    logoTextColor: "#ffffff",
  },
];
